server:
  port: 9000
spring:
  application:
    name: ad-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: route_path #payment_route   路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:7000
          #uri: lb://ad-sponsor #匹配后提供服务的路由地址
          predicates:
              - Path=/ad-sponsor/**     #断言，路径相匹配的进行路由


eureka:
  instance:
    hostname: ad-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/