server:
  port: 9000
spring:
  application:
    name: ad-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
#      routes:
#        - id: payment_routh  #payment_route   路由的ID，没有固定规则但要求唯一，建议配合服务名

eureka:
  instance:
    hostname: ad-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/