spring:
  application:
    name: ad-eureka
server:
  port: 8000


eureka:
  instance:
    hostname: server1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server2:8001/eureka/

